name: Auto_Sigin_163

on:
  # push:
  workflow_dispatch:
  # repository_dispatch:
  schedule:
    - cron: '30 1,6 * * *' # 每天9:30, 14:30执行，时间为国际标准时间 + 8 =北京时间！！

jobs:
  build:

    if: github.actor == github.repository_owner
    runs-on: ubuntu-latest
    container: node:16.16.0

    steps:
    - name: 'checkout codes'
      uses: actions/checkout@main
    - name: Run
      uses: GabrielBB/xvfb-action@v1
      with:
        run: dotnet run
        retention-days: 5
      env: 
        CONF: ${{ secrets.CONF }}
