name: Auto_Sigin_163

on:
  workflow_dispatch:
  # repository_dispatch:
  schedule:
    - cron: '18 1,8 * * *' # 每天9:30, 14:30执行，时间为国际标准时间 + 8 =北京时间！！

jobs:
  build:

    if: github.actor == github.repository_owner
    runs-on: ubuntu-latest

    steps:
    - name: 'checkout codes'
      uses: actions/checkout@main
    - name: Run
      uses: GabrielBB/xvfb-action@v1
      with:
        run: dotnet run
      env: 
        CONF: ${{ secrets.CONF }}